#!/usr/bin/env python3
"""Parse all SKILL.md files and compile them into docs/skills_data.js."""

import json
import re
from pathlib import Path
import yaml

ROOT = Path(__file__).parent.parent
SKILLS_DIR = ROOT / "skills"
OUTPUT_FILE = ROOT / "docs" / "skills_data.js"


def extract_skill_data(skill_dir: Path) -> dict:
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        return None

    content = skill_md.read_text(encoding="utf-8")

    # Split frontmatter and body
    match = re.match(r"^---\n(.*?)\n---\n(.*)", content, re.DOTALL)
    if not match:
        # Try matching without a trailing newline in case the file is short
        match = re.match(r"^---\n(.*?)\n---(.*)", content, re.DOTALL)

    if not match:
        print(f"Warning: No valid frontmatter found in {skill_md}")
        return None

    frontmatter_text = match.group(1)
    body_text = match.group(2).strip()

    try:
        fm = yaml.safe_load(frontmatter_text) or {}
    except Exception as e:
        print(f"Error parsing YAML in {skill_md}: {e}")
        fm = {}

    metadata = fm.get("metadata", {})
    if not isinstance(metadata, dict):
        metadata = {}

    return {
        "name": fm.get("name", skill_dir.name),
        "description": fm.get("description", ""),
        "version": metadata.get("version", "1.0.0"),
        "author": metadata.get("author", "unknown"),
        "category": metadata.get("category", "general"),
        "content": body_text,
    }


def main():
    if not SKILLS_DIR.exists():
        print(f"Skills directory not found: {SKILLS_DIR}")
        return 1

    skills_data = []
    for d in sorted(SKILLS_DIR.iterdir()):
        if not d.is_dir():
            continue
        data = extract_skill_data(d)
        if data:
            skills_data.append(data)

    # Ensure docs directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Write out as JS payload
    js_content = (
        "// This file is auto-generated by scripts/generate_site.py. DO NOT edit manually.\n"
        f"const SKILLS_DATA = {json.dumps(skills_data, indent=2, ensure_ascii=False)};\n"
    )
    OUTPUT_FILE.write_text(js_content, encoding="utf-8")

    print(f"Successfully generated {OUTPUT_FILE} with {len(skills_data)} skills.")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
